export { default } from "./src/wallet-manager-btc.js";
export { default as WalletAccountReadOnlyBtc } from "./src/wallet-account-read-only-btc.js";
export { default as WalletAccountBtc } from "./src/wallet-account-btc.js";
export { ISigner } from "@tetherto/wdk-wallet";
export type BtcTransactionReceipt = import("bitcoinjs-lib").Transaction;
export type FeeRates = import("@tetherto/wdk-wallet").FeeRates;
export type KeyPair = import("@tetherto/wdk-wallet").KeyPair;
export type TransactionResult = import("@tetherto/wdk-wallet").TransactionResult;
export type TransferOptions = import("@tetherto/wdk-wallet").TransferOptions;
export type TransferResult = import("@tetherto/wdk-wallet").TransferResult;
export type Finality = import("@tetherto/wdk-wallet").Finality;
export type TransactionReceipt = import("@tetherto/wdk-wallet").TransactionReceipt;
export type WaitForTransactionTarget = import("@tetherto/wdk-wallet").WaitForTransactionTarget;
export type WaitForTransactionOptions = import("@tetherto/wdk-wallet").WaitForTransactionOptions;
export type BtcTransaction = import("./src/wallet-account-read-only-btc.js").BtcTransaction;
export type BtcTransactionDetails = import("./src/wallet-account-read-only-btc.js").BtcTransactionDetails;
export type BtcWalletConfig = import("./src/wallet-account-read-only-btc.js").BtcWalletConfig;
export type BtcMaxSpendableResult = import("./src/wallet-account-read-only-btc.js").BtcMaxSpendableResult;
export type BtcTransfer = import("./src/wallet-account-btc.js").BtcTransfer;
export type SignerOptions = import("./src/wallet-account-btc.js").SignerOptions;
export type BtcClientConfig = import("./src/transports/index.js").BtcClientConfig;
export type BtcBalance = import("./src/transports/index.js").BtcBalance;
export type BtcUtxo = import("./src/transports/index.js").BtcUtxo;
export type BtcHistoryItem = import("./src/transports/index.js").BtcHistoryItem;
export type MempoolElectrumConfig = import("./src/transports/index.js").MempoolElectrumConfig;
export { IBtcClient, BlockbookClient, MempoolElectrumClient, ElectrumTcp, ElectrumSsl, ElectrumTls, ElectrumWs } from "./src/transports/index.js";
