name: build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  ELECTRS_VERSION_TAG: "0.10.10" # Don't use the reserved var name ELECTRS_VERSION
  BITCOIND_VERSION_TAG: "29.0"

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: tetherto/oss-actions/node-base@v1
      - run: npm run lint
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
    runs-on: ${{ matrix.os }}
    name: Test / ${{ matrix.platform }}
    steps:
      - uses: tetherto/oss-actions/node-base@v1
      - name: Install LLVM dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-dev libclang-dev clang pkg-config

      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env

      - name: Install bitcoind ${{ env.BITCOIND_VERSION_TAG }}
        run: |
          wget https://bitcoincore.org/bin/bitcoin-core-${{ env.BITCOIND_VERSION_TAG }}/bitcoin-${{ env.BITCOIND_VERSION_TAG }}-x86_64-linux-gnu.tar.gz
          tar -xzf bitcoin-${{ env.BITCOIND_VERSION_TAG }}-x86_64-linux-gnu.tar.gz
          sudo install -m 0755 -o root -g root -t /usr/local/bin bitcoin-${{ env.BITCOIND_VERSION_TAG }}/bin/*

      - name: Install electrs ${{ env.ELECTRS_VERSION_TAG }}
        run: |
          wget https://github.com/romanz/electrs/archive/refs/tags/v${{ env.ELECTRS_VERSION_TAG }}.tar.gz
          tar -xzf v${{ env.ELECTRS_VERSION_TAG }}.tar.gz
          cd electrs-${{ env.ELECTRS_VERSION_TAG }}
          cargo build --locked --release
          sudo install -m0755 target/release/electrs /usr/local/bin/

      - name: Run tests
        run: npm test
