name: build

on:
  push:
    branches: [main, develop, ci/test-env]
  pull_request:
    branches: [main, develop, ci/test-env]

env:
  NODE_VERSION: 22

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      - name: Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install LLVM dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-dev libclang-dev clang pkg-config

      - name: Install Bitcoin Core 29.0
        run: |
          wget https://bitcoincore.org/bin/bitcoin-core-29.0/bitcoin-29.0-x86_64-linux-gnu.tar.gz
          tar -xzf bitcoin-29.0-x86_64-linux-gnu.tar.gz
          sudo install -m 0755 -o root -g root -t /usr/local/bin bitcoin-29.0/bin/*

      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
      - name: Clone electrs
        run: git clone https://github.com/romanz/electrs.git
      - name: Build electrs
        run: |
          cd electrs
          cargo build --locked --release
      - name: Install electrs
        run: |
          sudo install -m0755 electrs/target/release/electrs /usr/local/bin/

      - name: Install dependencies
        run: npm clean-install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Lint code with standard
        run: npm run lint

      - name: Run tests
        run: npm test
